---
name: Sunny
surname: Tseng
position: "Data analyst, Infographic designer"
#pronouns: she/her
address: "Vancouver, Canada"
phone: +1 778-985-2258
www: sunshineland.netlify.app
email: "sunnyyctseng@gmail.com"
#twitter: mariecurie
#github: mariecurie
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```




# EDUCATION

```{r}
tribble(~ Degree, ~ Year, ~ Institution, ~ Where, ~ Additional,
  "Natural Resources & Environmental Studies", "Jan. 2021 - present", "Ph.D, University of Northern British Columbia", "Prince George, Canada", list("Supervisory committee: Ken A. Otter, Heather Bryan, Joseph Shea, and Dexter Hodder", "Thesis: Broad-scaled avian biodiversity assessment with passive acoustic monitoring"),
  
  "Forest Resources Management", "Sep. 2017 - Nov. 2019", "Master of Science, University of British Columbia", "Vancouver, Canada", list("Supervisory committee: Bianca N.I. Eskelson, Kathy Martin, and Nicholas C. Coops", "Thesis: Innovative and conventional modelling for avian acoustic and fire severity analyses"),
  
  "Double major in Physics and Forestry & Resource Conservation", "Sep. 2012 - Jun. 2017", "Bachelor of Science, National Taiwan University", "Taipei, Taiwan", list("Supervisor: Shi-Wei Chu", "Thesis: High spatio-temporal-resolution detection of chlorophyll fluorescence dynamics from a single chloroplast", "Forestry GPA: 3.96/4.0; Physics GPA: 3.40/4.0; Cumulative GPA: 3.65/4.0")
  
  ) %>%
  detailed_entries(Degree, Year, Institution, Where, Additional)
```

# PUBLICATION

## JOURNAL ARTICLES

## POPULAR SCIENCE ARTICLES

```{r}
tribble(
  ~ Year, ~ Title, ~ Journal,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    with = Type,
    when = Year,
    what = Desc
  )
```

## CONFERENCE TALKS

## CONFERENCE POSTERS



# WORK EXPERIENCE

# RECOGNITION


\newpage

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Extra, 
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland", "bla",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France", "bla1",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France", "bla2",
) %>%
  detailed_entries(Degree, Year, Institution, Where, Extra)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    with = glue::glue("Nobel Prize in {Type}"),
    when = Year,
    what = Desc
  )
```


